# Site settings
title: Colton's CS4375 Portfolio
author:
  name: Colton Townsend
  email: cxt180021@utdallas.edu
description: "My blog."

# Build settings
remote_theme: jekyll/minima

exclude:
- README.md
- LICENSE
- .gitignore
- .gitattributes
